import { GROUPS } from "./batch17-groups";
import { make } from "./batch17-lib";
import type { Entry } from "./batch12-lib";

/** batch37: generated by scripts/pcj-plan-batch.ts from batch37-plan.ts. Do not edit picks by hand; edit the plan and re-run. */
const paste = make(GROUPS.paste);
const tpad = make(GROUPS.tpad);
const revfan = make(GROUPS.revfan);
const fanhub = make(GROUPS.fanhub);
const argbctl = make(GROUPS.argbctl);
const riser37 = make(GROUPS.riser37);
const wifi = make(GROUPS.wifi);
const ups = make(GROUPS.ups);
const surge = make(GROUPS.surge);
const lightbar = make(GROUPS.lightbar);
const smat = make(GROUPS.smat);
const mic = make(GROUPS.mic);
const webcam = make(GROUPS.webcam);

export const batch37: Entry[] = [
  paste({ slug: "best-thermal-paste-for-gpu", kw: "thermal paste for GPU", asins: ["B09VDLH5M6","B09VDKSMQL","B09VDL3CW6","B0B1DMJQZ1"], seo: "Best Thermal Paste for GPU",
    lead: "A graphics card repaste needs a paste whose listing names GPU use and that does not conduct electricity if a little spreads onto the board. Every pick here names GPU or graphics-card use in its listing.",
    close: "Clean the old paste off the core with isopropyl alcohol and keep paste off the memory chips and the pad areas around the die." }),
  tpad({ slug: "best-thermal-pads-for-gpu", kw: "thermal pads for GPU", asins: ["B0BGH661Z2","B09JLHRSS9","B0BVDPGNLR","B06WWDT6RC","B07BSPZTNV"], seo: "Best Thermal Pads for GPU",
    lead: "Memory and VRM chips on a graphics card sit at different heights, so the pad's thickness matters as much as its conductivity rating. Every pick here lists its thickness and is sold as electrically non-conductive.",
    close: "Measure the old pads or look up a teardown of your exact card before buying, because the wrong thickness can leave memory uncooled." }),
  revfan({ slug: "best-reverse-blade-fans", kw: "reverse blade fans", asins: ["B0GC66NV13","B0FHQBNFSS","B0FV39D24F","B0F8QY1NKY","B0DB6LBS6T"], seo: "Best Reverse Blade Fans",
    lead: "Reverse-blade fans move air toward the back of the fan, so the lit side can face the glass panel while the fan still works as an intake. Every pick here is sold as a reverse-blade or reverse-airflow 120mm fan.",
    close: "Count how many reverse fans your intake positions need; side and bottom intakes are where the reverse design pays off." }),
  fanhub({ slug: "best-pwm-fan-hubs", kw: "PWM fan hubs", asins: ["B0887VG14J","B086X6WB4F","B0BZQ3NXMD","B0FBRNFLDM","B0D9434MLM"], seo: "Best PWM Fan Hubs",
    lead: "A fan hub lets one motherboard header run several fans, which matters when a case has more fans than headers. Every pick here lists how many fans it connects and what power it takes.",
    close: "Add up the current each fan draws from its label and keep the total inside the hub's stated limit." }),
  argbctl({ slug: "best-argb-controllers", kw: "ARGB controllers", asins: ["B0C7BG9RX4","B0CYWX2F35","B0DWMR6RXT","B0CWRJ578K","B09SZBJ5JZ"], seo: "Best ARGB Controllers",
    lead: "An ARGB controller adds lighting ports or lighting control beyond what the motherboard offers. Every pick here connects 5V 3-pin addressable devices and says how you control it.",
    close: "Match the 5V 3-pin plugs by their arrow marking; never connect an ARGB hub to a 12V 4-pin RGB header." }),
  riser37({ slug: "best-pcie-riser-cables", kw: "PCIe riser cables", asins: ["B0GY4LFD83","B0FX2RZ1MR","B0FJYLM8G8","B0GV53X4CN","B0GYSPN5MY"], seo: "Best PCIe Riser Cables",
    lead: "A riser cable moves the graphics card to a vertical mount, and the PCIe generation it supports decides whether a new card runs at full speed. Every pick here states its PCIe generation.",
    close: "Measure the path from the motherboard slot to the card's connector with a string before choosing a length." }),
  wifi({ slug: "best-pcie-wifi-cards", kw: "PCIe Wi-Fi cards", asins: ["B0D93H1CCR","B0DR3Y4FFF","B0DLYWPP7X","B0D33M6CB7","B0B4VH4G1C"], seo: "Best PCIe Wi-Fi Cards",
    lead: "A PCIe Wi-Fi card swaps a desktop's missing or weak wireless for a card with external antennas, and the Wi-Fi standard has to match your router to matter. Every pick here states its Wi-Fi standard.",
    close: "Check the board for a free PCIe x1 slot and a USB 9-pin header before you order, because Bluetooth uses that header." }),
  ups({ slug: "best-ups-for-gaming-pc", kw: "UPS for a gaming PC", asins: ["B00429N19W","B0BCMLLSHL","B08GRY1W93","B0C4R5JK74","B00429N192"], seo: "Best UPS for a Gaming PC",
    lead: "A gaming PC needs a UPS rated in watts well above its load, with sine wave output that suits active PFC power supplies. Every pick here states both its watt rating and a sine wave output.",
    close: "Add the PC's peak draw to the monitor and router, then stay under the unit's watt rating." }),
  surge({ slug: "best-surge-protectors-for-pc", kw: "surge protectors for a PC", asins: ["B0DB7V938J","B0CZJQDGKX","B0D1XH8NJP","B08BJWRZGY","B0BQNB74CF"], seo: "Best Surge Protectors for PC",
    lead: "A desk full of a PC, monitors and chargers needs outlets with room for bulky adapters and a stated surge rating. Every pick here lists its joule rating and outlet count.",
    close: "Plug nothing heavier than the strip's 15A limit into it and do not chain one strip into another." }),
  lightbar({ slug: "best-monitor-light-bars", kw: "monitor light bars", asins: ["B08DKQ3JG1","B0DRG3WXB3","B0C5JMWZC9","B076VNFZJG","B0GSPZ797T"], seo: "Best Monitor Light Bars",
    lead: "A monitor light bar aims light at the desk rather than the screen, so the clamp has to fit your monitor and the beam has to be asymmetric. Every pick here sits on the monitor and takes USB power.",
    close: "Check your monitor's thickness and curvature against the clamp range before buying." }),
  smat({ slug: "best-standing-desk-mats", kw: "standing desk mats", asins: ["B0F5NWQ5Y9","B07X2RP4DG","B0797Q5HL7","B07STF3P74","B0GX1HBMHM"], seo: "Best Standing Desk Mats",
    lead: "A standing desk mat adds cushioning under your feet, and thickness and grip decide whether it feels stable. Every pick here is sold for use at a standing desk.",
    close: "Size it so both feet sit on it, and keep it away from rolling chair casters." }),
  mic({ slug: "best-microphones-for-podcasting", kw: "microphones for podcasting", asins: ["B0CCV74CL7","B074HZFG3P","B0C46CS37H","B076WWQ4WT","B0CMZDPST3"], seo: "Best Microphones for Podcasting",
    lead: "Podcast microphones need to reject room noise and sit close to your mouth, which suits dynamic capsules and boom-arm kits. Every pick here is a dynamic microphone or ships with a boom arm.",
    close: "Speak a hand's width from the capsule and use a pop filter to keep plosives under control." }),
  mic({ slug: "best-xlr-microphones-under-100", kw: "XLR microphones under $100", asins: ["B0B8GRCXB6","B07MSCRCVK","B0BMFQP2ZZ"], seo: "Best XLR Microphones Under $100",
    lead: "An XLR microphone needs an audio interface or mixer, so the microphone is only part of the cost at this price. Every pick here has an XLR output and cost $100 or less when we checked.",
    close: "Budget for an interface and an XLR cable on top of the microphone." }),
  mic({ slug: "best-usb-microphones-under-50", kw: "USB microphones under $50", asins: ["B0C46CS37H","B0FLKJ7FH7","B0CCV74CL7"], seo: "Best USB Microphones Under $50",
    lead: "A USB microphone plugs straight into a PC and works without an interface, which suits a first streaming or call setup. Every pick here connects over USB and cost $50 or less when we checked.",
    close: "Check whether the microphone has a headphone jack if you want to hear yourself without delay." }),
  webcam({ slug: "best-webcams-for-twitch-streaming", kw: "webcams for Twitch streaming", asins: ["B0DS2JXD26","B0G63LXK6R","B0DMF4GLR8","B0GYQXZKZM","B09XRC3N91"], seo: "Best Webcams for Twitch Streaming",
    lead: "A Twitch webcam is judged on smooth motion at your stream resolution, not on a headline 4K figure. Every pick here lists a frame rate of 60fps or higher.",
    close: "Set the webcam's resolution and frame rate in OBS rather than leaving the default, and light your face from the front." }),
  webcam({ slug: "best-webcams-for-zoom", kw: "webcams for Zoom", asins: ["B08VJ25PL1","B0DQCW3L6D","B098GXD82C","B0CW1S7XP5","B09NBWWP79"], seo: "Best Webcams for Zoom",
    lead: "For Zoom the useful features are a stable 1080p picture and a way to cover the lens between calls. Every pick here lists 1080p or better and a privacy option.",
    close: "Zoom compresses video, so face a window or lamp instead of spending more on resolution." }),
];
