import { GROUPS } from "./batch17-groups";
import { make } from "./batch17-lib";
import type { Entry } from "./batch12-lib";

/** batch36: generated by scripts/pcj-plan-batch.ts from batch36-plan.ts. Do not edit picks by hand; edit the plan and re-run. */
const ssd36 = make(GROUPS.ssd36);
const m2sink = make(GROUPS.m2sink);
const nas = make(GROUPS.nas);
const hub = make(GROUPS.hub);
const usbcard = make(GROUPS.usbcard);
const microsd = make(GROUPS.microsd);
const stream36 = make(GROUPS.stream36);

export const batch36: Entry[] = [
  ssd36({ slug: "best-ssds-for-rog-ally", kw: "ssds for rog ally", asins: ["B0GP8YND8T","B0D61SDZD2","B0FD2LGBZF","B0FD2P1L37","B0FH4QHSVR"], seo: "Best SSDs for ROG Ally",
    lead: "The original ROG Ally takes a short M.2 2230 drive, so a standard 2280 SSD will not fit. We ordered 1TB and 2TB 2230 drives by listed read speed, since the Ally's PCIe 4.0 slot can use it.",
    close: "Check whether you own the original ROG Ally or the ROG Ally X before ordering; the X ships with a longer 2280 slot and takes different drives." }),
  ssd36({ slug: "best-ssds-for-steam-deck-oled", kw: "ssds for steam deck oled", asins: ["B0BVLNGPYB","B0DZX4T8TB","B0D61SDZD2","B0FD2P1L37","B0DBPTR3G3"], seo: "Best SSDs for Steam Deck OLED",
    lead: "The Steam Deck OLED takes a single-sided M.2 2230 NVMe drive, and a drive with no added heatsink leaves the original shield and thermal pad in place. Every pick is a 2230 drive without a bulky heatsink, ordered from the most capacity down.",
    close: "Back up your library, move the Deck's original shield and thermal pad across to the new drive, and reinstall SteamOS from Valve's recovery image." }),
  ssd36({ slug: "best-ssds-for-legion-go", kw: "ssds for legion go", asins: ["B0D2K9CQNK","B0D2KHFC8Y","B0F5BTQHGM","B0FGCD7PYD","B0D2KKKQL4"], seo: "Best SSDs for Legion Go",
    lead: "The Lenovo Legion Go uses a short M.2 2242 SSD, which is shorter than the 2280 drives in most PCs and longer than 2230. Every pick here is a 2242 NVMe drive, and Transcend and Corsair list the Legion Go by name.",
    close: "Confirm the 2242 length on your own unit and Lenovo's guidance before buying, and do not mix up 2242 with the 2230 drives sold for other handhelds." }),
  ssd36({ slug: "best-ssds-for-gaming-laptops", kw: "ssds for gaming laptops", asins: ["B0CK2TC9XQ","B0CK39YR9V","B0DN7CYYSD","B0DC8VPSHV","B0DC8RVRBZ"], seo: "Best SSDs for Gaming Laptops",
    lead: "A gaming laptop takes a bare M.2 2280 drive, since the lid leaves little room for a tall heatsink. Every pick lists laptop use, and we ordered them from the highest listed read speed down.",
    close: "Check whether your laptop has a second M.2 slot, whether it is PCIe 4.0, and whether the chassis allows double-sided drives before you buy." }),
  m2sink({ slug: "best-m2-ssd-heatsinks", kw: "m.2 ssd heatsinks", asins: ["B07YC1HTFR","B076YZMQR5","B09DBF8FX1","B09HRN8QXY","B0BNZYFW88"], seo: "Best M.2 SSD Heatsinks",
    lead: "A heatsink helps a fast M.2 drive hold its speed during long writes when your motherboard has no cover for it. We ordered these standalone heatsinks from the lowest listed height up, which matters most when a graphics card sits close to the slot.",
    close: "Measure the clearance above the M.2 slot, especially under a graphics card, and peel every film off the thermal pad before you fit it." }),
  ssd36({ slug: "best-sata-ssds", kw: "sata ssds", asins: ["B0F42NF2T3","B09ZYQ84CM","B08QBJ2YMG","B0BZMLG2CJ","B08QB93S6R"], seo: "Best SATA SSDs",
    lead: "A SATA SSD is the simplest upgrade for an older desktop, a laptop with a 2.5-inch bay or a secondary game drive. Every pick uses the SATA III interface, so rated speeds sit between 500MB/s and 560MB/s, so we ordered them by listed read speed and then by price.",
    close: "Check that you have a free 2.5-inch bay or bracket plus a SATA data port and a SATA power connector before you order." }),
  ssd36({ slug: "best-8tb-ssds", kw: "8tb ssds", asins: ["B089C3TZL9","B0D9WTM2TH","B0D9WT512W","B0FTMG6Y6X","B0GJF1GQFX"], seo: "Best 8TB SSDs",
    lead: "An 8TB SSD holds a very large game library or video archive on one drive. Every pick is listed at 8TB, and they range from SATA to PCIe 5.0, so check the slot and heat requirements.",
    close: "Check that your motherboard has an M.2 slot with room for the drive, and note the price per terabyte against two 4TB drives." }),
  nas({ slug: "best-nas-hard-drives", kw: "nas hard drives", asins: ["B0B94PNF7P","B07SGGWYC1","B0H5WGGZ9M","B0F4R6SNJG","B084ZV1DN6"], seo: "Best NAS Hard Drives",
    lead: "A NAS drive is built for years of 24/7 use inside a multi-drive enclosure, with firmware and vibration handling that desktop drives lack. We ordered these by capacity and noted recording type, workload rating and warranty from each listing.",
    close: "Check your NAS maker's compatibility list for the exact drive model, and keep a second copy of anything you cannot replace." }),
  hub({ slug: "best-usb-c-hubs-for-pc", kw: "usb-c hubs for pc", asins: ["B0G7XW6FKN","B0DX6KR79L","B0DY15GFNG","B0DT6Z3R4F","B087QZVQJX"], seo: "Best USB-C Hubs for PC",
    lead: "A USB-C hub moves your ports onto the desk, which helps a desktop PC where the rear I/O is out of reach. We ordered these from the most ports down, and several include their own power adapters.",
    close: "Check that your PC's USB-C port supports data, and whether it supports video, before relying on a hub's HDMI port." }),
  usbcard({ slug: "best-pcie-usb-expansion-cards", kw: "pcie usb expansion cards", asins: ["B0BSG6KWZ9","B0CM5L6X4K","B08PF8XR73","B09V6SFDZQ","B09ZKNJDNW"], seo: "Best PCIe USB Expansion Cards",
    lead: "A PCIe USB card adds ports to a desktop that has run out, with stronger power delivery than a hub. We ordered these by port count, and noted the speed of each port and which slot it needs.",
    close: "Count your free PCIe lanes and check which slots share bandwidth with M.2 drives before choosing a card with 10Gbps or 20Gbps ports." }),
  microsd({ slug: "best-microsd-cards-for-steam-deck", kw: "microsd cards for steam deck", asins: ["B0G8M74T13","B0G8LLK2HM","B0DQY9M2FR","B0DQYCG9D6","B0F29YZWSM"], seo: "Best microSD Cards for Steam Deck",
    lead: "The Steam Deck reads standard microSD cards over UHS-I, so an A2-rated UHS-I card is the right target and microSD Express would add cost without adding speed. We ordered cards from 256GB up by listed read speed.",
    close: "Format the card from the Deck's own settings, and keep your most-played games on the internal drive, which is faster than any microSD card." }),
  stream36({ slug: "best-capture-cards-for-switch-2", kw: "capture cards for switch 2", asins: ["B0H29LQLF6","B0GHV4K8ZF","B0F9FN7PYY","B0FFTFYGLV","B0CGD86HNB"], seo: "Best Capture Cards for Switch 2",
    lead: "The Nintendo Switch 2 has been on sale since June 2025, and capture cards need explicit support for it. Every pick lists Switch 2 compatibility in its title or bullets, and we ordered them from the lowest price up.",
    close: "Switch 2 docked output can reach 4K60 with HDR, so check each card's pass-through limits and use the HDMI cable and dock that came with your console." }),
];
