import { GROUPS } from "./batch17-groups";
import { make } from "./batch17-lib";
import type { Entry } from "./batch12-lib";

/** batch26: generated by scripts/pcj-plan-batch.ts from batch26-plan.ts. Do not edit picks by hand; edit the plan and re-run. */
const cpu = make(GROUPS.cpu);
const gkb = make(GROUPS.gkb);
const monitor = make(GROUPS.monitor);

export const batch26: Entry[] = [
  cpu({ slug: "best-cpu-for-fortnite", kw: "cpu for fortnite", asins: ["B0D6NN6TM7","B0BBHHT8LY","B0BMQJWBDM"], seo: "Best CPUs for Fortnite",
    lead: "Fortnite leans on a few fast cores, so boost clock matters more than core count. Every pick has six or more cores, boosts to 5.0GHz or more and cost $260 or less.",
    close: "Use performance mode with a high-refresh monitor; the CPU is the limit at low settings." }),
  cpu({ slug: "best-cpu-for-apex-legends", kw: "cpu for apex legends", asins: ["B0DWGWN8GY","B0DVZSG8D5","B0H2Z7VF4G","B0DFK2MH2D","B0CGJ4MLC8"], seo: "Best CPUs for Apex Legends",
    lead: "Apex Legends runs on an older engine that favours cache and clock speed in big fights. Every pick has at least eight cores and boosts to 5.3GHz or more, ordered by L3 cache.",
    close: "Cap the frame rate just under your monitor's refresh rate for steadier frame times." }),
  cpu({ slug: "best-cpu-for-call-of-duty-warzone", kw: "cpu for call of duty warzone", asins: ["B0BBHHT8LY","B0BMQK718H","B0D6NN87T8","B0DFK2MH2D"], seo: "Best CPUs for Call of Duty: Warzone",
    lead: "Warzone is one of the most CPU-heavy shooters, with large maps and many players. Every pick has eight or more cores and 16 or more threads and boosts to 5.4GHz or more, ordered from the lowest price.",
    close: "Keep the shader cache enabled and install the game on an NVMe SSD." }),
  cpu({ slug: "best-cpu-for-counter-strike-2", kw: "cpu for counter strike 2", asins: ["B0BBJ59WJ4","B0D6NN87T8","B0G8JMLXNQ","B0BBHHT8LY"], seo: "Best CPUs for Counter-Strike 2",
    lead: "Counter-Strike 2 is limited by one or two fast cores, so clock speed and cache decide frame rates. Every pick has 32MB or more of L3 and boosts to 5.4GHz or more, ordered by boost clock.",
    close: "A 360Hz monitor needs a CPU that holds frame rates well above 400 in this game." }),
  cpu({ slug: "best-cpu-for-dota-2", kw: "cpu for dota 2", asins: ["B0D6NN6TM7","B0BBJDS62N","B09VCJ171S"], seo: "Best CPUs for Dota 2",
    lead: "Dota 2 depends more on the processor than the graphics card in late-game fights. Every pick has six or more cores and cost $200 or less, ordered by boost clock.",
    close: "Spend the rest of the budget on faster RAM before a bigger GPU." }),
  cpu({ slug: "best-cpu-for-elden-ring", kw: "cpu for elden ring", asins: ["B0F9XH8DBP","B0BBJDS62N","B0CGJ4MLC8","B0B2X1KDNS"], seo: "Best CPUs for Elden Ring",
    lead: "Elden Ring is capped at 60fps by default, so any modern six-core chip is enough and the savings can go to the GPU. Every pick is a chip for a DDR5-capable platform with at least six cores that cost $240 or less.",
    close: "Put spare budget into the GPU; the 60fps cap means a faster CPU rarely adds frame rate." }),
  cpu({ slug: "best-cpu-for-escape-from-tarkov", kw: "cpu for escape from tarkov", asins: ["B0DWGWN8GY","B0DVZSG8D5","B0F9XH8DBP"], seo: "Best CPUs for Escape From Tarkov",
    lead: "Tarkov is CPU-bound on its large maps and benefits from big cache more than most games. Every pick has 96MB or more of L3 cache, ordered by cache size.",
    close: "Install Tarkov on an SSD; load times on large maps are long on a hard drive." }),
  cpu({ slug: "best-cpu-for-helldivers-2", kw: "cpu for helldivers 2", asins: ["B0CVZGD5M6","B0BMQK718H","B0CGJ9STNF","B0BCDR9M33","B0DFK2MH2D"], seo: "Best CPUs for Helldivers 2",
    lead: "Helldivers 2 spawns large groups of enemies, which use many threads. Every pick has eight or more cores and 16 or more threads and cost $350 or less, ordered by thread count.",
    close: "Keep the game on an SSD and update the GPU driver before big patches." }),
  cpu({ slug: "best-cpu-for-minecraft", kw: "cpu for minecraft", asins: ["B0CVZGD5M6","B0BBJ59WJ4","B0CGJDKLB8"], seo: "Best CPUs for Minecraft",
    lead: "Minecraft is mostly single-thread limited, so a high boost clock helps with big worlds and mods. Every pick boosts to 5.5GHz or more, ordered from the lowest price.",
    close: "Allocate more RAM to the Java launcher when you run heavy modpacks." }),
  cpu({ slug: "best-cpu-for-overwatch-2", kw: "cpu for overwatch 2", asins: ["B0D6NN6TM7","B0BBJDS62N","B0DFK8HHK4","B09VCHR1VH","B0B2X1KDNS"], seo: "Best CPUs for Overwatch 2",
    lead: "Overwatch 2 runs on a modest CPU, and high frame rates come from clock speed. Every pick has six or more cores and cost $180 or less, ordered by boost clock.",
    close: "Pair it with a high-refresh monitor; a 144Hz screen wastes a fast CPU." }),
  cpu({ slug: "best-cpu-for-rocket-league", kw: "cpu for rocket league", asins: ["B09VCJ171S","B0DT7CW7VR","B09VCHR1VH","B0BBJDS62N"], seo: "Best CPUs for Rocket League",
    lead: "Rocket League is a light esports title, so a budget six-core chip drives very high frame rates. Every pick has six or more cores and cost $170 or less, ordered from the lowest price.",
    close: "Check whether the chip includes a cooler before you add one to the cart." }),
  cpu({ slug: "best-cpu-for-microsoft-flight-simulator-2024", kw: "cpu for microsoft flight simulator 2024", asins: ["B0D6NNRBGP","B0DVZSG8D5","B0BBJ59WJ4","B0G8JMLXNQ"], seo: "Best CPUs for Flight Simulator 2024",
    lead: "Microsoft Flight Simulator 2024 pushes one main thread hard and also streams scenery data. Every pick has 64MB or more of L3 cache and boosts to 5.2GHz or more, ordered by boost clock.",
    close: "Use 32GB of RAM for large photogrammetry cities." }),
  gkb({ slug: "best-gaming-keyboards-for-fps", kw: "gaming keyboards for fps", asins: ["B0FBWHYLL3","B0FGXK7X6F","B0GQLPPTW5","B0D9Y83J89","B0F2GVF5HC"], seo: "Best Gaming Keyboards for FPS Games",
    lead: "Shooters reward fast key response and desk space for wide mouse swipes. Every pick is a compact or TKL board with 8000Hz polling or optical or magnetic switches, ordered by polling rate.",
    close: "Set the actuation point low only for movement keys; accidental presses cost rounds." }),
  monitor({ slug: "best-gaming-monitors-for-small-desk", kw: "gaming monitors for small desk", asins: ["B0GV5JZG1Q","B0CP9MBSXW","B0F73CV58N","B0FY4LVHYH","B0FSB6WX8J"], seo: "Best Gaming Monitors for Small Desks",
    lead: "A small desk limits how big a screen you can sit in front of. Every pick is 25 inches or smaller with a refresh rate of 144Hz or more, ordered by refresh rate.",
    close: "Check the stand footprint; a monitor arm frees desk depth." }),
  gkb({ slug: "best-gaming-keyboards-for-small-hands", kw: "gaming keyboards for small hands", asins: ["B0D3CZYCH2","B099PTK6PY","B089GN2KBT","B0DT43NNNF","B0DSMWJD6M"], seo: "Best Gaming Keyboards for Small Hands",
    lead: "A 60% or 65% board is narrower, so your hands travel less between the keys and the mouse. Every pick has a compact layout of 68 keys or fewer, ordered from the lowest price.",
    close: "Check the layout for a dedicated arrow cluster if you rely on it; some 60% boards hide arrows behind a layer." }),
];
