import { GROUPS } from "./batch17-groups";
import { make } from "./batch17-lib";
import type { Entry } from "./batch12-lib";

/** batch31: generated by scripts/pcj-plan-batch.ts from batch31-plan.ts. Do not edit picks by hand; edit the plan and re-run. */
const fanrad = make(GROUPS.fanrad);
const fan = make(GROUPS.fan);
const fan140 = make(GROUPS.fan140);
const combo = make(GROUPS.combo);

export const batch31: Entry[] = [
  fanrad({ slug: "best-radiator-fans", kw: "radiator fans", asins: ["B0CSSXZKJB","B0D49L67NS","B0H2XBQ3RR","B0D49NN28D","B0C8LN919S"],
    lead: "A radiator pushes back harder than an open case, so a radiator fan is judged on static pressure, the force that moves air through dense fins, more than on raw airflow. Every pick here lists a pressure rating of at least 2 mmH2O or is described by its maker as built for radiators.",
    close: "Check the radiator's fan size and thickness first: most take 25mm-thick 120mm or 140mm fans, and a thicker 30mm fan can clash with the case or the memory." }),
  fan({ slug: "best-120mm-case-fans", kw: "120mm case fans", asins: ["B0GVQMQ915","B0H2XBQ3RR","B0CSSXZKJB","B0D49QX74S","B0C8M192HS"],
    lead: "The 120mm fan is the default size for case intake and exhaust, so the useful comparison is rated airflow against noise and how many fans you get in the box. Every pick here is a 120mm fan that lists a CFM rating, ordered from the highest rating down.",
    close: "A rating is the maker's own figure at full speed, so choose two or three fans that suit your case's mount positions and let the motherboard's fan curve keep them below full speed." }),
  fan140({ slug: "best-140mm-case-fans", kw: "140mm case fans", asins: ["B0DGGKQFM6","B0FV3CLQVS","B0D49P65L2","B0D49NN28D","B00KF7O58G"],
    lead: "A 140mm fan covers more area than a 120mm at the same speed, so it can move similar air more quietly, but it needs a case with 140mm mounts. Every pick here is a 140mm fan, ordered by the number of fans in the box.",
    close: "Look for 140mm mount holes in the front and top of the case before ordering; many cases take 140mm fans only in some positions." }),
  combo({ slug: "best-keyboard-and-mouse-for-office-and-gaming", kw: "keyboard and mouse for office and gaming", asins: ["B0H6QCWZST","B0GVP4J6XG","B0DL9WC26F","B0D8MD5RLL","B0DH2H1DS9"], seo: "Best Keyboard and Mouse, Office and Gaming",
    lead: "A keyboard and mouse that has to serve both a work day and an evening of games needs a sensor with room above the office default and a battery that outlasts both. Every pair here is wireless and lists a mouse sensitivity of at least 3,200 DPI.",
    close: "Check the keyboard's layout against your desk space and whether the receiver or Bluetooth pairing suits your PC before buying; a full-size keyboard with a number pad takes the most room." }),
  fan({ slug: "best-cpu-cooler-fans", kw: "cpu cooler fans", asins: ["B0H2XBQ3RR","B0D49L67NS","B0BWKZGYXJ","B07CG2PGY6","B0BMTHQ4H4"],
    lead: "A replacement or second fan for a CPU tower or radiator needs enough static pressure to push air through dense fins, and a mounting size that matches the cooler's clips. Every pick here is a 120mm single fan or a two-pack that lists either a pressure rating of 1.5 mmH2O or more or a top speed of 1,500 RPM or more.",
    close: "Measure the fan's thickness against your cooler's clearance and check whether the cooler's clips take the fan's frame before ordering." }),
];
